-- TRANSACTION para alterar nomes das colunas extraídas incorretamenta
BEGIN TRANSACTION;

DROP TABLE TEMP_FAV;

ALTER TABLE FAVORECIDO RENAME TO TEMP_FAV;

CREATE TABLE FAVORECIDO (
    `NIS_FAVORECIDO` VARCHAR(15) NOT NULL,
    `NOME_FAVORECIDO` VARCHAR(50) NULL,
    `MUNICIPIO_CODIGO_SIAFI_MUNICIPIO` VARCHAR(4) NOT NULL,
    PRIMARY KEY (`NIS_FAVORECIDO`),
    CONSTRAINT `fk_FAVORECIDO_MUNICIPIO`
    FOREIGN KEY (`MUNICIPIO_CODIGO_SIAFI_MUNICIPIO`)
    REFERENCES `MUNICIPIO` (`CODIGO_SIAFI_MUNICIPIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE UNIQUE INDEX `NIS_FAVORECIDO_UNIQUE` ON `FAVORECIDO`
(`NIS_FAVORECIDO` ASC);

CREATE INDEX `fk_FAVORECIDO_MUNICIPIO_idx` ON `FAVORECIDO`
(`MUNICIPIO_CODIGO_SIAFI_MUNICIPIO` ASC);

INSERT INTO FAVORECIDO (NIS_FAVORECIDO, NOME_FAVORECIDO, MUNICIPIO_CODIGO_SIAFI_MUNICIPIO)
SELECT NOME_FAVORECIDO, MUNICIPIO_CODIGO_SIAFI_MUNICIPIO, NIS_FAVORECIDO
FROM TEMP_FAV;

DROP TABLE TEMP_FAV;

commit;
