-- TRANSACTION para alterar nomes das colunas extraídas incorretamenta
BEGIN TRANSACTION;

DROP TABLE TEMP_FAV;

ALTER TABLE FAVORECIDO RENAME TO TEMP_FAV;

CREATE TABLE FAVORECIDO (
    `NIS_FAVORECIDO` VARCHAR(15) NOT NULL,
    `NOME_FAVORECIDO` VARCHAR(50) NULL,
    `ODIGO_SIAFI_MUNICIPIO` VARCHAR(4) NOT NULL,
    PRIMARY KEY (`NIS_FAVORECIDO`));

INSERT INTO FAVORECIDO (NIS_FAVORECIDO, NOME_FAVORECIDO, CODIGO_SIAFI_MUNICIPIO)
SELECT NOME_FAVORECIDO, CODIGO_SIAFI_MUNICIPIO, NIS_FAVORECIDO
FROM TEMP_FAV;

DROP TABLE TEMP_FAV;

commit;
