DROP TABLE IF EXISTS `PAGAMENTO` ;

-- -----------------------------------------------------
-- Table `PAGAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PAGAMENTO` (
  `PROGRAMA_CODIGO_PROGRAMA` VARCHAR(4) NOT NULL,
  `FAVORECIDO_NIS_FAVORECIDO` VARCHAR(15) NOT NULL,
  `MES_COMPETENCIA` VARCHAR(10) NOT NULL,
  `VALOR_PARCELA` INTEGER NULL,
  PRIMARY KEY (`PROGRAMA_CODIGO_PROGRAMA`, `FAVORECIDO_NIS_FAVORECIDO`, `MES_COMPETENCIA`),
  CONSTRAINT `fk_PROGRAMA_has_FAVORECIDO_PROGRAMA1`
    FOREIGN KEY (`PROGRAMA_CODIGO_PROGRAMA`)
    REFERENCES `PROGRAMA` (`CODIGO_PROGRAMA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROGRAMA_has_FAVORECIDO_FAVORECIDO1`
    FOREIGN KEY (`FAVORECIDO_NIS_FAVORECIDO`)
    REFERENCES `FAVORECIDO` (`NIS_FAVORECIDO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_PROGRAMA_has_FAVORECIDO_FAVORECIDO1_idx` ON `PAGAMENTO` (`FAVORECIDO_NIS_FAVORECIDO` ASC);

CREATE INDEX `fk_PROGRAMA_has_FAVORECIDO_PROGRAMA1_idx` ON `PAGAMENTO` (`PROGRAMA_CODIGO_PROGRAMA` ASC);

insert into PAGAMENTO (PROGRAMA_CODIGO_PROGRAMA, FAVORECIDO_NIS_FAVORECIDO, MES_COMPETENCIA, VALOR_PARCELA) values
    ("1335", "00016352718710", "09/2015", 100),
    ("1335", "00012796886702", "09/2015", 200),
    ("1335", "00016529139185", "09/2015", 300),
    ("1335", "00012158641314", "09/2015", 400),
    ("1335", "00012158641314", "08/2015", 500);
